#!/usr/bin/env python3
"""Generate src/bluenoise.rs: a 64x64 void-and-cluster blue-noise
threshold mask (Ulichney 1993), toroidal gaussian energy, incremental
energy-field updates so the whole thing runs in seconds."""
import numpy as np

N = 64
SIGMA = 1.9
rng = np.random.default_rng(42)

dx = np.minimum(np.arange(N), N - np.arange(N))
d2 = dx[:, None] ** 2 + dx[None, :] ** 2
kernel = np.exp(-d2 / (2 * SIGMA * SIGMA))  # kernel[dy][dx], toroidal


def shifted(y, x):
    return np.roll(np.roll(kernel, y, axis=0), x, axis=1)


def field(mask):
    e = np.zeros((N, N))
    for y, x in zip(*np.nonzero(mask)):
        e += shifted(y, x)
    return e


def tightest_cluster(mask, e):
    masked = np.where(mask, e, -np.inf)
    return np.unravel_index(np.argmax(masked), masked.shape)


def largest_void(mask, e):
    masked = np.where(mask, np.inf, e)
    return np.unravel_index(np.argmin(masked), masked.shape)


# initial pattern: ~10% random minority pixels, relaxed to a fixpoint
mask = np.zeros((N, N), dtype=bool)
idx = rng.choice(N * N, N * N // 10, replace=False)
mask.flat[idx] = True
e = field(mask)
while True:
    cy, cx = tightest_cluster(mask, e)
    mask[cy, cx] = False
    e -= shifted(cy, cx)
    vy, vx = largest_void(mask, e)
    if (vy, vx) == (cy, cx):
        mask[cy, cx] = True
        e += shifted(cy, cx)
        break
    mask[vy, vx] = True
    e += shifted(vy, vx)

rank = np.zeros((N, N), dtype=np.int32)
ones = int(mask.sum())

# phase 1: peel tightest clusters -> ranks ones-1 .. 0
work = mask.copy()
ew = e.copy()
for r in range(ones - 1, -1, -1):
    cy, cx = tightest_cluster(work, ew)
    work[cy, cx] = False
    ew -= shifted(cy, cx)
    rank[cy, cx] = r

# phase 2: fill largest voids -> ranks ones .. N*N-1
work = mask.copy()
ew = e.copy()
for r in range(ones, N * N):
    vy, vx = largest_void(work, ew)
    work[vy, vx] = True
    ew += shifted(vy, vx)
    rank[vy, vx] = r

vals = (rank * 256) // (N * N)  # 0..255
lines = []
for y in range(N):
    lines.append("    " + ", ".join(str(int(v)) for v in vals[y]) + ",")
out = (
    "// 64x64 void-and-cluster blue-noise threshold mask (values 0..255).\n"
    "// Generated by bench/gen_bluenoise.py (sigma=1.9, seed=42); do not\n"
    "// hand-edit.\n"
    "pub const BLUE_NOISE_64: [u8; 4096] = [\n" + "\n".join(lines) + "\n];\n"
)
with open("src/bluenoise.rs", "w") as f:
    f.write(out)
print(f"mask written: mean={vals.mean():.1f} min={vals.min()} max={vals.max()}")
